config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  
  delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'
  
  resources :repositories

  match '/fetch', to: 'repositories#create', via: 'get'

end

app/models/repository.rb
class Repository < ActiveRecord::Base
	
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

	before_action :set_auth
	before_action :set_repository, only: [:show]

	def index
	end

	def new
		a = Octokit::Client.new(access_token: "#{params[:token]}", per_page: 200)
		@results = a.repositories
	end

	def create
		@fetch = Fetch.new
		@rep = @fetch.repo_bus_factor(params[:token], params[:repos])
		if @rep.is_a? Integer
			redirect_to repository_path(@rep)
		else
			redirect_to new_repository_path(token: params[:token]), notice: "Something went wrong!!"
		end
	end

	def show
	end


	private

	def set_repository
      @repository = Repository.find(params[:id])
    end

	
	def set_auth
		@auth = session[:omniauth] if session[:omniauth]
	end

end

app/views/repositories/new.html.erb
<h1>Choose your repository</h1>

	<%= form_tag fetch_path, :method => 'get', class: "navbar-form navbar-left"  do %>
		<%= select_tag 'repos', options_for_select(@results.collect{ |u| [u["full_name"]] }) %>
		<%= hidden_field_tag :token, @auth['credentials']['token'] %>
    	<%= submit_tag "HitMewithABus!", :name => nil, class: "btn btn-default" %>
    <% end %>

app/views/repositories/show.html.erb
	<div class="list-group">
	  <button type="button" class="list-group-item"><b><%= @repository.bus_factor_string %></b></button>
	  <button type="button" class="list-group-item"><b>Repository:</b> <%= @repository.repos_url %></button>
	  <button type="button" class="list-group-item"><b>Releases: </b><%= @repository.releases %></button>
	  <button type="button" class="list-group-item"><b>PRS: </b><%= @repository.prs %></button>
	  <button type="button" class="list-group-item"><b>Refactoring: </b><%= @repository.refactoring %></button>
	  <button type="button" class="list-group-item"><b>Stars: </b><%= @repository.stars %></button>
	  <button type="button" class="list-group-item"><b>Watchers: </b><%= @repository.watchers %></button>
	  <button type="button" class="list-group-item"><b>Forks: </b><%= @repository.forks %></button>
	</div>

	<%= link_to "Check another repository", root_path, data: { no_turbolink: true } %>